sudo: false
cache: bundler
bundler_args: --retry=3 --jobs=3
language: ruby
before_install:
  # https://github.com/travis-ci/travis-ci/issues/8978#issuecomment-354036443
  - gem update --system
  - gem install bundler
rvm:
  - 2.7.1
  - 2.6.6
  - 2.5.8
  - ruby-head
  - jruby-9.2.11.1
  - jruby-head
  - rbx-2
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.2.11.1
    - rvm: jruby-head
    - rvm: rbx-2
  fast_finish: true
